### PR TITLE
set Debug in Config struct, use that as condition to log extra inform…

### PR DESCRIPTION
**Pull request by zsiddique**
…ation

### CODE REVIEW

**Review by blake-wilson — COMMENTED** [review]
Makes sense, but in order to have fewer conflicts as we update this with the upstream changes, should we just set `reporter.Silence = true` when our application is in debug mode?

**Comment by zsiddique** [comment]
you mean setting `Silence = true` when not in debug mode.  TBH I had to make a few other changes like returning errors vs just printing them.  I think we could merge those changes upstream if the author is willing to accept them.

**Comment by mike-zorn** [comment]
Why is it that the built-in `reporter.Silence` isn't working for us? I doubt the author would accept this PR since it's just replacing the existing mechanism they have for silencing logs.

**Comment by zsiddique** [comment]
I guess I just liked having all my configs in the Config struct but its, not a hard issue.  I will close this PR and have an update for fmetric instead

**Pull request closed without merging**
